name: duration_picker_dialog_box
description: A Duration Picker for selecting Duration and set the various Duration fields - Days, Hours, Minutes, Seconds, MilliSeconds, MicroSeconds.
version: 1.0.1
homepage: https://github.com/ashutosh2014/duration_picker_dialog_box
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:

